//
//  DummyMovies.swift
//  Movie App
//
//  Created by Rangga Djatikusuma Lukman on 15/04/20.
//  Copyright © 2020 Lukman Solution. All rights reserved.
//

import Foundation
import UIKit

struct DummyData {
    static let movies: [Movie] = [
        Movie(id: 1, title: "A Star Is Born", poster_path: UIImage(named: "poster_a_start_is_born")!, release_date: "2018-10-05", vote_average: "7.5", description: "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons."),
        Movie(id: 2, title: "Alita: Battle Angle", poster_path: UIImage(named: "poster_alita")!, release_date: "2019-01-31", vote_average: "6.9", description: "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past."),
        Movie(id: 3, title: "Aquaman", poster_path: UIImage(named: "poster_aquaman")!, release_date: "2018-12-07", vote_average: "6.8", description: "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne."),
        Movie(id: 4, title: "Bohemian Rhapsody", poster_path: UIImage(named: "poster_bohemian")!, release_date: "2018-10-24", vote_average: "8.0", description: "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess."),
        Movie(id: 5, title: "Cold Persuit", poster_path: UIImage(named: "poster_cold_persuit")!, release_date: "2019-02-07", vote_average: "5.4", description: "The quiet family life of Nels Coxman, a snowplow driver, is upended after his son's murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking's associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution."),
        Movie(id: 6, title: "Creed", poster_path: UIImage(named: "poster_creed")!, release_date: "2015-11-25", vote_average: "7.4", description: "The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed."),
        Movie(id: 7, title: "Fantastic Beasts: The Crimes of Grindelwald", poster_path: UIImage(named: "poster_crimes")!, release_date: "2018-11-14", vote_average: "6.8", description: "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world."),
        Movie(id: 8, title: "Glass", poster_path: UIImage(named: "poster_glass")!, release_date: "2019-01-16", vote_average: "6.5", description: "In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men."),
        Movie(id: 9, title: "How To Train Your Dragon: The Hidden World", poster_path: UIImage(named: "poster_how_to_train")!, release_date: "2019-01-03", vote_average: "7.7", description: "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind."),
        Movie(id: 10, title: "Avengers: Infinity War", poster_path: UIImage(named: "poster_infinity_war")!, release_date: "2018-04-25", vote_average: "8.3", description: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.")
    ]
    
    static let tvshows: [Tvshow] = [
        Tvshow(id: 1, name: "The Arrow", poster_path: UIImage(named: "poster_arrow")!, first_air_date: "2012-10-10", vote_average: "5.9", description: "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow."),
        Tvshow(id: 2, name: "Marvel's Iron Fist", poster_path: UIImage(named: "poster_iron_fist")!, first_air_date: "2017-03-17", vote_average: "6.1", description: "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny."),
        Tvshow(id: 3, name: "Dragon Ball", poster_path: UIImage(named: "poster_dragon_ball")!, first_air_date: "1986-02-26", vote_average: "7.3", description: "Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the mystical Dragon Balls brought her to Goku's home. Together, they set off to find all seven and to grant her wish."),
        Tvshow(id: 4, name: "Fairy Tail", poster_path: UIImage(named: "poster_fairytail")!, first_air_date: "2009-10-12", vote_average: "6.7", description: "Lucy is a 17-year-old girl, who wants to be a full-fledged mage. One day when visiting Harujion Town, she meets Natsu, a young man who gets sick easily by any type of transportation. But Natsu isn't just any ordinary kid, he's a member of one of the world's most infamous mage guilds: Fairy Tail."),
        Tvshow(id: 5, name: "Family Guy", poster_path: UIImage(named: "poster_family_guy")!, first_air_date: "1999-01-31", vote_average: "6.6", description: "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues."),
        Tvshow(id: 6, name: "The Flash", poster_path: UIImage(named: "poster_flash")!, first_air_date: "2014-10-07", vote_average: "6.9", description: "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash."),
        Tvshow(id: 7, name: "Naruto Shippūden", poster_path: UIImage(named: "poster_naruto_shipudden")!, first_air_date: "2007-02-15", vote_average: "7.9", description: "Naruto Shippuuden is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as He has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki."),
        Tvshow(id: 8, name: "Gotham", poster_path: UIImage(named: "poster_gotham")!, first_air_date: "2014-09-22", vote_average: "7.0", description: "Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?"),
        Tvshow(id: 9, name: "Grey's Anatomy", poster_path: UIImage(named: "poster_grey_anatomy")!, first_air_date: "2005-03-27", vote_average: "6.7", description: "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital."),
        Tvshow(id: 10, name: "Hanna", poster_path: UIImage(named: "poster_hanna")!, first_air_date: "2019-03-28", vote_average: "7.0", description: "This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.")
    ]
    
    static let banners: [UIImage] = [UIImage(named: "banner_one")!, UIImage(named: "banner_two")!, UIImage(named: "banner_three")!]
}
